spring:
  datasource:
    url: jdbc:mysql://192.168.36.136:3306/imooc_parent2?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    #url: jdbc:mysql://192.168.75.128:3306/imooc_parent2?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: dog
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:imooc/*.xml                 #classpath*:标识resource目录下
  mapper-scan: com.imooc.server.mapper               #src目录下扫描
  type-aliases-package: com.imooc.server.bo      #实体类包
  global-config:
    db-config:
      db-type: mysql
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



