#http://localhost:8761

spring:
  profiles:
    include: logging
  application:
    name: imooc-erueka
  security:
    user:
      name: root
      password: root
      #roles: SUPERUSER


server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  server:
    enable-self-preservation: false #简单粗暴把自我保护模式关闭 参考为什么关闭:https://www.cnblogs.com/gudi/p/8645370.html
