
#eureka客户端连接配置
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    #将ip注册到eureka上
    prefer-ip-address: true
    #微服务向eureka注册实例名${spring.cloud.client.ip-address} 表示ip地址 spring2.0以上为ip-address
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
